config/routes.rb
Rails.application.routes.draw do
  resources :inicios

   root 'inicios#index'

end

app/models/inicio.rb
class Inicio < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inicios_controller.rb
class IniciosController < ApplicationController
  before_action :set_inicio, only: [:show, :edit, :update, :destroy]

  # GET /inicios
  # GET /inicios.json
  def index
    @inicios = Inicio.all
  end

  # GET /inicios/1
  # GET /inicios/1.json
  def show
  end

  # GET /inicios/new
  def new
    @inicio = Inicio.new
  end

  # GET /inicios/1/edit
  def edit
  end

  # POST /inicios
  # POST /inicios.json
  def create
    @inicio = Inicio.new(inicio_params)

    respond_to do |format|
      if @inicio.save
        format.html { redirect_to @inicio, notice: 'Inicio was successfully created.' }
        format.json { render :show, status: :created, location: @inicio }
      else
        format.html { render :new }
        format.json { render json: @inicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inicios/1
  # PATCH/PUT /inicios/1.json
  def update
    respond_to do |format|
      if @inicio.update(inicio_params)
        format.html { redirect_to @inicio, notice: 'Inicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @inicio }
      else
        format.html { render :edit }
        format.json { render json: @inicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inicios/1
  # DELETE /inicios/1.json
  def destroy
    @inicio.destroy
    respond_to do |format|
      format.html { redirect_to inicios_url, notice: 'Inicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inicio
      @inicio = Inicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inicio_params
      params.require(:inicio).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicios_helper.rb
module IniciosHelper
end

app/views/inicios/_form.html.erb
<%= form_for(@inicio) do |f| %>
  <% if @inicio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inicio.errors.count, "error") %> prohibited this inicio from being saved:</h2>

      <ul>
      <% @inicio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inicios/edit.html.erb
<h1>Editing inicio</h1>

<%= render 'form' %>

<%= link_to 'Show', @inicio %> |
<%= link_to 'Back', inicios_path %>

app/views/inicios/index.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Brand
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => "#"}
            Link
            %span.sr-only (current)
        %li
          %a{:href => "#"} Link
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider
            %li
              %a{:href => "#"} Separated link
            %li.divider
            %li
              %a{:href => "#"} One more separated link
      %form.navbar-form.navbar-left{:role => "search"}
        .form-group
          %input.form-control{:placeholder => "Search", :type => "text"}
        %button.btn.btn-default{:type => "submit"} Submit
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "#"} Link
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider
            %li
              %a{:href => "#"} Separated link
  / /.navbar-collapse
  / /.container-fluid

.col-sm-12
  %h1
    Inclan
    %small
      Municipalidad

.container-fluid
  / left
  .col-sm-3
    %h2 Side
    .panel.panel-default
      .panel-heading Title
      .panel-body
        Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
        Aliquam in felis sit amet augue.
    %hr
      .panel.panel-default
        .panel-heading Title
        .panel-body Content here..
      %hr
        .panel.panel-default
          .panel-heading Title
          .panel-body
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
            Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
            dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
            Aliquam in felis sit amet augue.
        %hr
          .panel.panel-default
            .panel-heading Title
            .panel-body Content here..
          %hr
  / /left
  / center
  .col-sm-6
    .row
      .col-xs-12
        %h2 Article Heading
        %p
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
          Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
          dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
          Aliquam in felis sit amet augue.
        %p.lead
          %button.btn.btn-default Read More
        %p.pull-right
          %span.label.label-default keyword
          %span.label.label-default tag
          %span.label.label-default post
        %ul.list-inline
          %li
            %a{:href => "#"} 2 Days Ago
          %li
            %a{:href => "#"}
              %i.glyphicon.glyphicon-comment
              2 Comments
          %li
            %a{:href => "#"}
              %i.glyphicon.glyphicon-share
              14 Shares
    %hr
      .row
        .col-xs-12
          %h2 Article Heading
          %p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
            Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
            dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
            Aliquam in felis sit amet augue.
          %p.lead
            %button.btn.btn-default Read More
          %p.pull-right
            %span.label.label-default keyword
            %span.label.label-default tag
            %span.label.label-default post
          %ul.list-inline
            %li
              %a{:href => "#"} 4 Days Ago
            %li
              %a{:href => "#"}
                %i.glyphicon.glyphicon-comment
                7 Comments
            %li
              %a{:href => "#"}
                %i.glyphicon.glyphicon-share
                56 Shares
      %hr
        .row
          .col-xs-12
            %h2 Article Heading
            %p
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
              Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
              dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
              Aliquam in felis sit amet augue.
            %p.lead
              %button.btn.btn-default Read More
            %p.pull-right
              %span.label.label-default keyword
              %span.label.label-default tag
              %span.label.label-default post
            %ul.list-inline
              %li
                %a{:href => "#"} 1 Week Ago
              %li
                %a{:href => "#"}
                  %i.glyphicon.glyphicon-comment
                  4 Comments
              %li
                %a{:href => "#"}
                  %i.glyphicon.glyphicon-share
                  34 Shares
        %hr
  / /center
  / right
  .col-sm-3
    %h2 Side
    .panel.panel-default
      .panel-heading Title
      .panel-body
        Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
        Aliquam in felis sit amet augue.
    %hr
      .panel.panel-default
        .panel-heading Title
        .panel-body Content here..
      %hr
        .panel.panel-default
          .panel-heading Title
          .panel-body
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
            Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
            dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
            Aliquam in felis sit amet augue.
        %hr
          .panel.panel-default
            .panel-heading Title
            .panel-body Content here..
          %hr
  / /right
  %hr
  / /container-fluid

app/views/inicios/new.html.erb
<h1>New inicio</h1>

<%= render 'form' %>

<%= link_to 'Back', inicios_path %>

app/views/inicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inicio.name %>
</p>

<%= link_to 'Edit', edit_inicio_path(@inicio) %> |
<%= link_to 'Back', inicios_path %>

app/views/layouts/application.haml
!!!
%html{'ng-app' => 'Todo'}
  %head
    %title ToDo Rails and Angular
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .principal
      .sprincipal
        .container
          = yield